# Generated by Django 5.1.5 on 2025-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
