# Generated by Django 5.1.5 on 2025-02-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('chat', '0005_message_sender_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_ip',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
