# Generated by Django 5.1.5 on 2025-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Online'), (1, 'Offline')], default=1),
        ),
    ]
